version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      babel:
        patterns:
          - '@babel/*'

      lint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - 'standard'
          - 'stylelint'
          - 'stylelint-*'
          - 'typescript'

      metalsmith:
        patterns:
          - '@metalsmith/*'
          - 'jstransformer-*'
          - 'marked'
          - 'marked-*'
          - 'metalsmith'
          - 'metalsmith-*'

      postcss:
        patterns:
          - 'autoprefixer'
          - 'postcss'
          - 'postcss-*'

      rollup:
        patterns:
          - '@rollup/*'
          - 'rollup'

      test:
        patterns:
          - '@axe-core/*'
          - '@jest/*'
          - '@types/jest'
          - '@types/jest-*'
          - 'jest'
          - 'jest-*'
          - 'puppeteer'

      types:
        patterns:
          - '@types/*'

        # Exclude packages in other groups
        exclude-patterns:
          - '@types/jest'
          - '@types/jest-*'

    # Ignore eslint and is plugins for now
    # the time they all get compatible with each other
    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'

    reviewers:
      - alphagov/design-system-developers

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - alphagov/design-system-developers

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
