blank_issues_enabled: true
contact_links:
  - name: Get in touch another way
    url: https://hmlr-design-system-staging.herokuapp.com/get-in-touch/
    about: Find out how to get in touch via email or Slack
