name: Test

on:
  pull_request:
  push:
    branches-ignore:
      - main  # pushes to main are handled by deploy.yaml

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            upload-artifact: ${{ inputs.upload-artifact }}
    runs-on: ${{ matrix.os }}
    env:
      ENVIRONMENT: production

    steps:
      - uses: actions/checkout@v2

      - name: Read node version from .nvmrc
        id: nvm
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-optional

      - name: Build
        run: npm run build

      - name: Lint and test
        run: npm test -- --runInBand
