name: Test

on:
  pull_request:

  push:
    branches-ignore:
      - main  # pushes to main are handled by deploy.yaml

jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    env:
      ENVIRONMENT: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint and test
        run: npm test -- --color --maxWorkers=2
